---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/pks-kubectl

inputs:
- name: pcf-lab-pipelines

run:
  path: pcf-lab-pipelines/tasks/all/pks-create-cluster/task.sh

params:
  PKS_API:
  PKS_CLI_USERNAME:
  PKS_CLI_PASSWORD:
  PKS_SERVICE_PLAN_NAME:
  PKS_CLUSTER_NAME:
  PKS_CLUSTER_MASTER_HOSTNAME:
  PKS_CLUSTER_NUMBER_OF_WORKERS: