---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
inputs:
  - name: pcf-lab-pipelines 
  - name: terraform-state
  - name: ami
outputs:
  - name: terraform-state-output
params:
  aws_access_key_id:
  aws_secret_access_key:
  aws_key_name:
  aws_region: 
  OPSMAN_ALLOW_SSH_CIDR_RANGES:
  OPSMAN_ALLOW_HTTPS_CIDR_RANGES:
run:
  path: pcf-lab-pipelines/pipelines/install-pks/aws/tasks/prepare-aws/task.sh